In [4]:
import pandas as pd

# df = pd.read_csv('Friends_A_vad.tsv', sep='\t')
df = pd.read_csv('CPED_A_VAD.tsv', sep='\t')
df.head()

,speaker,dialog_state,emotions,sent,utterance,context,A,C,E,O,N,labels,VAD_personality,Emoberta_softmax
0,童文洁,"[1, 1, 0, 1]","['neutral', 'neutral', 'neutral', 'neutral']","['what a coincidence', 'the car is fine', ""It'...","what a coincidence the car is fine It's okay, ...","It's you, it's okay, it's okay, thank you",0,1,1,0,1,0,"[0.5234849999999999, 0.37201, 0.62677500000000...","[[0.13834500312805176, 0.43881726264953613, 0...."
1,刘静,"[0, 0, 1, 0]","['neutral', 'neutral', 'neutral', 'neutral']","['what a coincidence', 'the car is fine', ""It'...","It's you, it's okay, it's okay, thank you","what a coincidence the car is fine It's okay, ...",1,1,1,1,0,1,"[0.7517499999999999, 0.46436, 0.69402, 0.10434...","[[0.13834500312805176, 0.43881726264953613, 0...."
2,刘静,"[1, 0, 1]","['neutral', 'neutral', 'neutral']","['right', 'Your kids go to school here too', '...",right Yes,Your kids go to school here too,1,1,1,1,0,1,"[0.5319799999999999, 0.4498, 0.79464, 0.300146...","[[0.5381240844726562, 0.08701325207948685, 0.0..."
3,童文洁,"[0, 1, 0]","['neutral', 'neutral', 'neutral']","['right', 'Your kids go to school here too', '...",Your kids go to school here too,right Yes,0,1,1,0,1,0,"[0.5501766666666666, 0.3545666666666667, 0.584...","[[0.5381240844726562, 0.08701325207948685, 0.0..."
4,童文洁,"[1, 1, 0, 1]","['neutral', 'neutral', 'neutral', 'neutral']","['What a coincidence my son is here', 'what gr...",What a coincidence my son is here what grade i...,senior year,0,1,1,0,1,0,"[0.5493028571428571, 0.3871285714285714, 0.638...","[[0.05369448661804199, 0.23863549530506134, 0...."

In [5]:
df.shape

(23794, 14)

In [13]:
df_EmoBERTa = pd.DataFrame(EmoBERTa_labels)
df_EmoBERTa[0].value_counts()

neutral    6850
joy         922
anger       384
sadness       1
Name: 0, dtype: int64